Backend/Models/LeagueView.cs
using Domain;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Backend.Models
{
    [NotMapped]
    public class UserView : User
    {
        [Display(Name="Logo")]
        public HttpPostedFileBase LogoFile { get; set; }

    }
}

Backend/Controllers/LeaguesController.cs
using Backend.Helpers;
using Backend.Models;
using Domain;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;

namespace Backend.Controllers
{
    [Authorize]
    public class LeaguesController : Controller
    {
        private DataContextLocal db = new DataContextLocal();
         FilesHelper fileshelper = new FilesHelper();
        public async Task<ActionResult> DeleteTeam(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var team = await db.Teams.FindAsync(id);

                if (team == null)
                {
                    return HttpNotFound();
                }

                db.Teams.Remove(team);
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("Details/{0}", team.LeagueId));
            } 
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }
        public async Task<ActionResult> EditTeam(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var team = await db.Teams.FindAsync(id);

                if (team == null)
                {
                    return HttpNotFound();
                }

                var view = ToView(team);
                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditTeam(TeamView view)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var pic = view.Logo;
                    var folder = "~/Content/Logos";

                    if (view.LogoFile != null)
                    {
                        pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                        pic = string.Format("{0}/{1}", folder, pic);
                    }

                    var team = ToTeam(view);
                    team.Logo = pic;
                    db.Entry(team).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction(string.Format("Details/{0}", view.LeagueId));
                }

                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
                
            }
        }
        public async Task<ActionResult> CreateTeam(int? id)
        {
            try
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var league = await db.Leagues.FindAsync(id);

                if (league == null)
                {
                    return HttpNotFound();
                }

                var view = new TeamView { LeagueId = league.LeagueId, };
                return View(view);
            }
            catch (Exception ex)
            {

                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTeam(TeamView view)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var pic = string.Empty;
                    var folder = "~/Content/Logos";

                    if (view.LogoFile != null)
                    {
                        pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                        pic = string.Format("{0}/{1}", folder, pic);
                    }

                    var team = ToTeam(view);
                    team.Logo = pic;
                    db.Teams.Add(team);
                    await db.SaveChangesAsync();
                    return RedirectToAction(string.Format("Details/{0}", view.LeagueId));
                }

                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        private Team ToTeam(TeamView view)
        {
            return new Team
            {
                Initials = view.Initials,
                League = view.League,
                LeagueId = view.LeagueId,
                Logo = view.Logo,
                Name = view.Name,
                TeamId = view.TeamId,

            };
        }
        private TeamView ToView(Team team)
        {
            return new TeamView
            {
                Initials = team.Initials,
                League = team.League,
                LeagueId = team.LeagueId,
                Logo = team.Logo,
                Name = team.Name,
                TeamId = team.TeamId,

            };

        }
        public async Task<ActionResult> Index()
        {
            return View(await db.Leagues.ToListAsync());
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var league = await db.Leagues.FindAsync(id);
            if (league == null)
            {
                return HttpNotFound();
            }
            return View(league);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LeagueView view)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var pic = string.Empty;
                    var folder = "~/Content/Logos";

                    if (view.LogoFile != null)
                    {
                        pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                        pic = string.Format("{0}/{1}", folder, pic);
                    }

                    var league = ToLeague(view);
                    league.Logo = pic;
                    db.Leagues.Add(league);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }

                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        private League ToLeague(LeagueView view)
        {
            return new League
            {
                LeagueId = view.LeagueId,
                Logo = view.Logo,
                Name = view.Name,
                Teams = view.Teams,
            };
        }

        public async Task<ActionResult> Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var league = await db.Leagues.FindAsync(id);

                if (league == null)
                {
                    return HttpNotFound();
                }

                var view = ToView(league);
                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        private LeagueView ToView(League league)
        {
            return new LeagueView
            {
                LeagueId = league.LeagueId,
                Logo = league.Logo,
                Name = league.Name,
                Teams = league.Teams,
            };
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LeagueView view)
        {

            if (ModelState.IsValid)
            {

                var pic = view.Logo;
                var folder = "~/Content/Logos";

                if (view.LogoFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.LogoFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var league = ToLeague(view);
                league.Logo = pic;
                db.Entry(league).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            try
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                League league = await db.Leagues.FindAsync(id);
                if (league == null)
                {
                    return HttpNotFound();
                }

                return View(league);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            League league = await db.Leagues.FindAsync(id);
            db.Leagues.Remove(league);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {

Backend/Views/Leagues/Create.cshtml
@model Backend.Models.LeagueView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>League</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoFile, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Leagues/CreateTeam.cshtml
@model Backend.Models.TeamView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("CreateTeam", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LeagueId)


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to League", "Details", new { id = Model.LeagueId }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Leagues/Delete.cshtml
@model Domain.League

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
        </div>
    }
</div>

Backend/Views/Leagues/Details.cshtml
@model Domain.League

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit League", "Edit", new { id = Model.LeagueId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Create Team", "CreateTeam", new { id = Model.LeagueId }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
</p>

<h4>Teams</h4>
@if (Model.Teams.Count == 0)
{
    <h5>No temas registered yet</h5>
}
else
{
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Logo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teams.FirstOrDefault().Initials)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Teams.OrderBy(t => t.Name))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @if (!string.IsNullOrEmpty(item.Logo))
                    {
                        <img src="@Url.Content(item.Logo)" alt="Image" style="width:80px;height:80px;max-width: 100%; height: auto;" />
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Initials)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditTeam", new { id = item.TeamId }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Delete", "DeleteTeam", new { id = item.TeamId }, new { @class = "btn btn-danger",  onclick = "return confirm('Are you sure to delete this record');" })
                </td>
            </tr>
        }

    </table>

}

Backend/Views/Leagues/Edit.cshtml
@model Backend.Models.LeagueView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>League</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LeagueId)
        @Html.HiddenFor(model => model.Logo)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
                @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Leagues/EditTeam.cshtml
@model Backend.Models.TeamView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("EditTeam", "Leagues", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeamId)
        @Html.HiddenFor(model => model.LeagueId)
        @Html.HiddenFor(model => model.Logo)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.LogoFile, new { type = "file" })
                </span>
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Initials, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Initials, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Initials, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
                @Html.ActionLink("Back to League", "Details", new { id = Model.LeagueId }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Leagues/Index.cshtml
@model IEnumerable<Domain.League>

@{
    ViewBag.Title = "Index";
}

<h2>Leagues</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th>
          # Teams    
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.Logo))
            {
                <img src="@Url.Content(item.Logo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teams.Count)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.LeagueId },  new { @class = "btn btn-warning" }) 
            @Html.ActionLink("Details", "Details", new { id=item.LeagueId }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id=item.LeagueId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>